Update README
fdcl-data-driven-control/data-driven-control pull request #9
Opened 2021-12-31 05:04 UTC by JinraeKim

2021-12-31 05:05 UTC, hnlee77 approved these changes

2021-12-31 05:06 UTC, hnlee77 requested changes
@JinraeKim 서브모듈에 대한 것도 넣어줄래요? ㅎㅎ

2021-12-31 05:08 UTC, JinraeKim commented
@hnlee77 어떤 맥락인지 잘 모르겠는데, 간단한거면 부탁드려도 될까요? 지금 이동중이라 ㅎ

2021-12-31 05:14 UTC, hnlee77 commented on README.md
> +
## Submodules 
- [DataDrivenControl.jl](https://github.com/fdcl-data-driven-control/DataDrivenControl.jl) : A julia package for data-driven-control.

2021-12-31 05:15 UTC, hnlee77 commented
내가 여기서 저걸 커밋을 못하네?

2022-01-01 05:59 UTC, JinraeKim commented
> 내가 여기서 저걸 커밋을 못하네?

저도 웹 상에서는 안되네요...?

2022-01-01 05:59 UTC, JinraeKim commented
> 내가 여기서 저걸 커밋을 못하네?

아 뭐야 코드 수정이 아니라 그냥 답글을 단거네요 ㅋㅋ

2022-01-01 06:00 UTC, JinraeKim commented on README.md
> +
```suggestion
## Submodules 
- [DataDrivenControl.jl](https://github.com/fdcl-data-driven-control/DataDrivenControl.jl) : A julia package for data-driven-control.
```

2022-01-01 06:01 UTC, JinraeKim commented on README.md
> +### Institute
```suggestion
## Institute
```

2022-01-01 06:01 UTC, JinraeKim commented
@hnlee77 해결했으니 approve 좀

2022-01-01 06:02 UTC, JinraeKim commented on README.md
> +- [DataDrivenControl.jl](https://github.com/fdcl-data-driven-control/DataDrivenControl.jl) : A julia package for data-driven-control.
```suggestion
- [DataDrivenControl.jl](https://github.com/fdcl-data-driven-control/DataDrivenControl.jl) : A Julia package for data-driven control.
```

2022-01-01 06:12 UTC, hnlee77 approved these changes

2022-01-01 06:13 UTC, merged